title: Hamilton Tobon Mosquera's Projects
description: This website showcases the side projects I've been working on for the last years.

remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
