title: Hamilton Tobon Mosquera's Projects
description: This website showcases the side projects I've been working on the last years.
remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme
