title: Hamilton Tobon Mosquera's Projects
description: Descriptions and links to my programming projects.
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
